export const ADD_FAVORITED_CARTOON = 'ADD_FAVORITED_CARTOON';
export const REMOVE_FAVORITED_CARTOON = 'REMOVE_FAVORITED_CARTOON';
export const POPULATE_FAVORITED_CARTOONS = 'POPULATE_FAVORITED_CARTOONS';
